-- Minimální návrhový checklist; není executable runtime DDL ani živý backlog.
-- Autorita pravidel: docs/README.md. Technický model:
-- docs/architecture/02-database-model.md. Skutečný bootstrap/upgrade:
-- docker/db/init/ (připojený docker-compose.yml).
--
-- user_account: jediná USER/ADMIN identita, unikátní username a normalizovaný
-- neveřejný e-mail, bezpečný password hash; žádný samostatný admin/coauthors.
-- sentence: stabilní kontejner s jedním neměnným ownerem.
-- sentence_revision: immutable skutečný vstup v draft_json, owner submitter,
-- unikátní monotónní revision_no; tokeny, syntax, evidence zůstávají v snapshotu.
-- validation_result: konkrétní revize, rules/validator version, serverový verdict,
-- skóre, result_json; immutable; klientské odvozeniny nejsou autorita.
-- rules_release: immutable runtime SHA-256 + validator version; explicitní active
-- release ve společných app/data; bez automatické revalidace/engine registry.
-- administrative_decision: jediný standardní approve/return/reject konkrétní
-- immutable revize; admin, důvod, čas, správná sentence/revision.
-- morphology_review_case + morphology_review_decision: interní rules-scoped
-- exact identita/morfologie/povrch, APPROVED/REJECTED (absence=UNKNOWN),
-- append-only opravy; validation_result_review odkazuje na použité stabilní ID.
-- real_word_catalog: oddělená lexikální autorita bez rules scope; úplný exact key,
-- schválení, zdroj/důvod, admin, čas. Hráčské exact API patří #102.
-- login_throttle: pouze krátkodobé operační čítače, žádná audit platforma.
--
-- Nezavádět compliance evidence/prohlášení, generic audit/provenance graf,
-- DB snapshoty, event sourcing, tokeny mailových funkcí před #104–#106,
-- povinné ručně vyplněné paradigma ani reachability filtr modelové nabídky.
-- Prefix/POS/NFC/score odvozuje server podle versioned validátoru; pomocné být
-- zůstává samostatný surface-valid a score-bearing token jediného přísudku.
