-- Nejdelší kvazivěta — target database schema checklist
-- PostgreSQL
--
-- IMPORTANT:
-- This file intentionally does NOT contain executable production DDL yet.
-- The previous pre-audit schema was retired after the 19/19 product decisions,
-- because it encoded now-invalid concepts (comment magic links, separate admin_user,
-- mutable sentence-level approval state, mixed user/catalog analysis truth, etc.).
--
-- Git history contains the old draft. Do not restore it as an implementation default.
-- Production/migration DDL must be created from the current architecture and the
-- implementation issues listed below after the remaining normative field schemas
-- and paradigms are finalized.

-- -----------------------------------------------------------------------------
-- CURRENT AUTHORITATIVE ARCHITECTURE
-- -----------------------------------------------------------------------------
-- docs/architecture/01-system-architecture.md
-- docs/architecture/02-database-model.md
-- docs/architecture/03-validation.md
-- docs/architecture/04-comments-auth-admin.md
-- docs/rules/04-verzovani-a-sprava.md
-- docs/governance/decisions.md

-- -----------------------------------------------------------------------------
-- REQUIRED TARGET DOMAINS
-- -----------------------------------------------------------------------------

-- 1. Rules releases
--    - rule_version
--    - immutable manifest items + per-artifact hash
--    - optional manifest hash and Git commit/tag metadata
--    - versioned normative enums/models/paradigms
--    See #9, #18, #27, #44.

-- 2. Registered users and auth
--    - one user account table with unique username + unique private email
--    - secure password hash only
--    - roles USER / ADMIN on the same account identity
--    - password-reset tokens stored only in safe derived form
--    - session/recovery/security model
--    There is NO separate admin_user table and NO magic-link login.
--    See #35, #36, #37.

-- 3. Sentences, drafts and immutable submissions
--    - sentence = long-lived container bound to author user_id
--    - editable draft
--    - each submit creates immutable sentence_revision
--    - review/submission verdicts bind to a revision, never only to sentence
--    - explicit sentence type with punctuation invariant:
--        DECLARATIVE -> '.'
--        INTERROGATIVE -> '?'
--        IMPERATIVE -> '!'
--    See #21, #22, #30.

-- 4. Token/word occurrence declarations
--    - stable token ID inside one immutable revision
--    - position + surface form + normalized NFC form
--    - player-declared analysis is stored separately from catalog-resolved truth
--    - complete field schema is POS/model-driven
--    - full proposed morphology paradigm + snapshot-bound confirmation
--    - structured evidence/source links
--    See #5, #23, #24, #26, #48, #53.

-- 5. Syntax
--    - ordinary dependent member: exactly one head
--    - predicate: no head
--    - supplement: predicate + subject/object links
--    - coordination: two distinct member links
--    - prepositions k/v/z: technical preposition role + exactly one governed nominal link;
--      no main sentence function on the preposition itself
--    - DB constraints must prevent links across sentence revisions
--    See #28, #51.

-- 6. Learning internal catalog
--    - catalog knowledge is scoped to one rules_version
--    - effective semantics APPROVED / REJECTED / UNKNOWN
--    - UNKNOWN may be represented by absence of a decision row
--    - new rules_version starts with no automatically inherited approvals
--    - decision provenance: exact identity/form, rules_version, admin user_id,
--      timestamp, reason, evidence and reproducible catalog state/revision
--    - approved/rejected history is never silently overwritten
--    See #6, #19, #20.

-- 7. Validation and review
--    Keep separate:
--    a) content/rule validity of a sentence_revision for a rules_version,
--    b) historical process compliance of the original submission,
--    c) administrative recognition/publication.
--
--    Each decisive validation result must carry full provenance, including:
--    - sentence_revision
--    - rules_version
--    - catalog snapshot/revision/provenance
--    - validator_version
--    - automatic/manual origin
--    - timestamp and deciding admin when relevant
--
--    Score belongs to the validation for a rules_version if scoring semantics vary.
--    See #17, #20, #40.

-- 8. Canonical text and scoring
--    - ordered revision tokens + sentence-type punctuation are source of truth
--    - cached sentence text / normalized text / score, if stored, are server-generated
--      and must be deterministically checkable against canonical data
--    See #22, #40.

-- 9. Admin audit
--    - admin is user_account with ADMIN role
--    - sensitive actions logged with actor user_id, action, entity, before/after
--      (or equivalent diff), reason and timestamp
--    See #36.

-- -----------------------------------------------------------------------------
-- EXPLICITLY OUT OF MVP / MUST NOT REAPPEAR IN INITIAL MIGRATIONS
-- -----------------------------------------------------------------------------
-- - comments
-- - commenter_identity / email_hmac / public_alias
-- - comment_magic_link
-- - separate admin_user identity
-- - public/pre-submit internal catalog membership endpoint
-- - automatic inheritance of catalog approvals across rules versions

-- -----------------------------------------------------------------------------
-- GATES BEFORE WRITING PRODUCTION MIGRATIONS
-- -----------------------------------------------------------------------------
-- 1. Finalize normative noun/adjective paradigms and reachable variants (#1, #4).
-- 2. Finalize reachable verb conjugation types (#2, #4).
-- 3. Finalize complete form field schema (#5).
-- 4. Represent paradigms/versioned normative enums without hidden UI rules (#18, #27).
-- 5. Implement DB integrity/provenance issues #17–#28, #30, #35–#45 as applicable.
-- 6. Review concrete MVP query paths and indexes with EXPLAIN (#45).
--
-- Until these gates are satisfied, this file is a schema design checklist,
-- not an executable migration.
