// Integration test targeting the real PHP runtime.
// Requires a running PHP + Docker stack. Set KVAZI_BASE_URL to override the default.
// Usage: PLAYWRIGHT_MODULE=/path/to/playwright/index.mjs node app/tests/konfigurator.browser.mjs
// Default base URL: http://127.0.0.1:8080 (matches `php -S 127.0.0.1:8080 -t app/public`)
import assert from 'node:assert/strict';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE || 'playwright');
const baseUrl = (process.env.KVAZI_BASE_URL || 'http://127.0.0.1:8080').replace(/\/$/, '');

let browser;
try {
  browser = await chromium.launch({ headless: true, ...(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {}) });
  const page = await browser.newPage();
  const errors = [];
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(`${baseUrl}/konfigurator.php`);
  await page.getByLabel('Typ věty', { exact: true }).selectOption('interrogative');
  await page.getByLabel('Nové slovo (bez mezer)').fill('vazi');
  await page.getByRole('button', { name: 'Vložit slovo', exact: true }).click();
  await page.getByLabel('Slovní druh', { exact: true }).selectOption('noun');
  await page.getByLabel('Základní tvar', { exact: true }).pressSequentially('testnoun');
  assert.equal(await page.getByLabel('Základní tvar', { exact: true }).inputValue(), 'testnoun');
  await page.getByLabel('Deklarovaná identita').selectOption('quasi');
  await page.getByLabel('Soutěžní vzor').selectOption('hrad');
  await page.getByLabel('Pád použitého tvaru').selectOption('1');
  await page.getByLabel('Číslo použitého tvaru').selectOption('singular');
  await page.getByLabel('Větná funkce', { exact: true }).selectOption('subject');
  await page.getByLabel('Morfologická obhajoba a odkaz na model').fill('Test evidence');
  await page.getByRole('button', { name: 'Zkopírovat text slova do prázdných buněk' }).click();
  assert.equal(await page.locator('[data-cell]').count(), 14);
  const confirm = page.getByRole('button', { name: 'Potvrzuji, že toto je můj morfologický návrh.', exact: true });
  assert.equal(await confirm.isEnabled(), true);
  await confirm.click();
  assert.equal(await page.getByText('Aktuální návrh je potvrzen uživatelem.', { exact: true }).count(), 1);
  await page.locator('[data-cell]').first().fill('other');
  assert.equal(await page.getByText('Aktuální návrh není potvrzen.', { exact: true }).count(), 1);
  await confirm.click();
  await page.getByRole('button', { name: 'Vložit za toto slovo', exact: true }).click();
  await page.getByLabel('Nové slovo (bez mezer)').fill('kvazi');
  await page.getByRole('button', { name: 'Vložit slovo', exact: true }).click();
  await page.getByLabel('Slovní druh', { exact: true }).selectOption('verb');
  await page.getByLabel('Vid', { exact: true }).selectOption('biaspectual');
  assert.equal(await page.locator('[data-cell]').count(), 0);
  assert.equal(await page.getByLabel('Soutěžní časovací typ').isDisabled(), true);
  await page.getByLabel('Větná funkce', { exact: true }).selectOption('predicate');
  await page.locator('#token-t1').click();
  await page.getByLabel('Řídící slovo', { exact: true }).selectOption('t2');
  await page.getByRole('button', { name: 'Vložit před toto slovo', exact: true }).click();
  await page.getByLabel('Nové slovo (bez mezer)').fill('k');
  await page.getByRole('button', { name: 'Vložit slovo', exact: true }).click();
  assert.equal(await page.getByLabel('Slovní druh', { exact: true }).inputValue(), 'preposition');
  assert.equal(await page.getByLabel('Slovní druh', { exact: true }).isDisabled(), true);
  await page.getByLabel('Řízené jmenné slovo').selectOption('t1');
  await page.locator('#token-t1').click();
  assert.equal(await page.getByLabel('Řídící slovo', { exact: true }).inputValue(), 't2');
  await page.getByLabel('Text slova', { exact: true }).fill('va\u0301zi');
  assert.equal(await page.getByLabel('Text slova', { exact: true }).inputValue(), 'vázi');
  assert.equal(await page.getByLabel('Základní tvar', { exact: true }).inputValue(), '');
  assert.equal(await page.getByLabel('Řídící slovo', { exact: true }).inputValue(), 't2');
  await page.getByRole('button', { name: 'Zobrazit náhled JSON (neodesílá)' }).click();
  const payload = JSON.parse(await page.locator('#payload pre').textContent());
  assert.deepEqual(payload.draft.tokens.map(w => w.id), ['t3', 't1', 't2']);
  assert.equal(payload.validation.submitReady, false);
  assert.equal(payload.submitted, false);
  assert.equal(payload.validation.text, 'k vázi kvazi?');
  // Every enabled form input has an explicit, associated label.
  assert.deepEqual(await page.locator('input, select, textarea').evaluateAll(nodes => nodes.filter(n => !n.labels?.length).map(n => n.id)), []);
  await page.getByLabel('Text slova', { exact: true }).fill('<img src=x onerror=alert(1)>');
  assert.equal(await page.locator('#payload pre').count(), 0);
  assert.equal(await page.locator('#editor img, #tokens img').count(), 0);
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await page.screenshot({ path: '/private/tmp/kvazi-configurator-mobile.png', fullPage: true });
  await page.goto(`${baseUrl}/konfigurator.php`);
  const entry = page.getByLabel('Nové slovo (bez mezer)');
  await entry.pressSequentially('vazi kvazi ');
  assert.equal(await page.locator('#tokens .token-chip').count(), 2);
  assert.equal(await entry.inputValue(), '');
  assert.equal(await entry.evaluate(el => el === document.activeElement), true);
  await entry.press('Backspace');
  assert.equal(await page.locator('#tokens .token-chip').count(), 1);
  await entry.pressSequentially('qazi');
  await entry.press('Backspace');
  assert.equal(await entry.inputValue(), 'qaz');
  assert.equal(await page.locator('#tokens .token-chip').count(), 1);
  await entry.press('Enter');
  assert.equal(await page.locator('#tokens .token-chip').count(), 2);
  await page.locator('#token-t1').click();
  await page.getByRole('button', { name: 'Vložit před toto slovo', exact: true }).click();
  await entry.pressSequentially('k v ');
  assert.deepEqual(await page.locator('#tokens [data-action="select"]').evaluateAll(nodes => nodes.map(n => n.id)), ['token-t4', 'token-t5', 'token-t1', 'token-t3']);
  await page.getByRole('button', { name: 'Smazat 3. slovo vazi', exact: true }).click();
  assert.deepEqual(await page.locator('#tokens [data-action="select"]').evaluateAll(nodes => nodes.map(n => n.id)), ['token-t4', 'token-t5', 'token-t3']);
  assert.equal(await entry.evaluate(el => el === document.activeElement), true);
  await entry.press('Space');
  assert.equal(await page.locator('#tokens .token-chip').count(), 3);
  assert.deepEqual(errors, []);
  console.log('Browser checks passed: editing, insertion, stable links, NFC, confirmation, gates, preview, labels, mobile overflow and escaped input.');
} finally {
  await browser?.close();
}
